### PR TITLE
Updated shoelace to version 2.14.0 and updated other dependencies

### PR DESCRIPTION
**Pull request by aglasencnik**
Updated shoelace to version 2.14.0 and updated other dev dependencies.
Also changed build script to: `webpack --mode production` because the old one was throwing errors.

### CODE REVIEW

**Comment by claviska** [comment]
Closing because I don't think you meant to push this upstream.

**Comment by claviska** [comment]
Thanks for the PR. Shoelace no longer uses Stencil or webpack so many of those dependencies are stale. This will require more work to update.

To be honest, we were thinking of removing the webpack and rollup examples because they don't seem to get much use. Did you find this helpful at all? Or would you have if it were kept up to date?

**Comment by aglasencnik** [comment]
@claviska the thing is, I am currently making a blazor wrapper for these components, and bundled js and css with webpack...

**Comment by claviska** [comment]
I'll be happy to reopen this if you want to continue updating it but, as it stands, the PR includes dependencies that just aren't used anymore. It's been so long since this has been touched that it will probably need to be rewritten to support the latest version of webpack, etc.

**Comment by aglasencnik** [comment]
Yeah, than its probably for the better if it is closed, as I dont have a lot of knowledge with this stuff (c#...😅)

**Comment by claviska** [comment]
FWIW, we've changed how imports work to improve a lot of the quirks we were seeing in earlier versions. In most cases, simply importing each component directly will just work these days. (The import code can be found in each component's docs.)

I hope that helps!

**Pull request closed without merging**
